# 1. Carga y estructuración de datos

In [5]:
# Importar la librería NumPy
import numpy as np


# Para que los resultados sean reproducibles, fijamos una semilla para el generador de números aleatorios.
np.random.seed(42)

# Creamos un array de NumPy con datos financieros simulados.
# Generamos números aleatorios entre 100 y 200 para simular precios de acciones.
# La función np.random.rand(5, 5) crea una matriz de 5x5 con valores entre 0 y 1.
# La multiplicamos por 100 y le sumamos 100 para que los precios sean más realistas.
precios_acciones = 100 + 100 * np.random.rand(5, 5)
# Organizamos los datos en una matriz de 5x5.
# Cada fila (axis=0) representa una acción.
# Cada columna (axis=1) representa un día de cotización.

print("1. Matriz de Precios de Acciones (5 Acciones x 5 Días)")
# Usamos np.round(2) para redondear los precios a dos decimales y facilitar la lectura.
print(np.round(precios_acciones, 2))

1. Matriz de Precios de Acciones (5 Acciones x 5 Días)
[[137.45 195.07 173.2  159.87 115.6 ]
 [115.6  105.81 186.62 160.11 170.81]
 [102.06 196.99 183.24 121.23 118.18]
 [118.34 130.42 152.48 143.19 129.12]
 [161.19 113.95 129.21 136.64 145.61]]


# 2. Análisis y transformación de datos

In [7]:


# a) Obtener el promedio, valor máximo y mínimo de cada acción a lo largo del tiempo.
# Usamos el argumento axis=1 para realizar los cálculos a través de las columnas (días) para cada fila (acción).
promedio_por_accion = np.mean(precios_acciones, axis=1)
maximo_por_accion = np.max(precios_acciones, axis=1)
minimo_por_accion = np.min(precios_acciones, axis=1)

print("\nPromedio de cada acción:")
print(np.round(promedio_por_accion, 2))

print("\nValor máximo de cada acción:")
print(np.round(maximo_por_accion, 2))

print("\nValor mínimo de cada acción:")
print(np.round(minimo_por_accion, 2))


# b) Calcular la variación porcentual diaria de cada acción.
# Fórmula: (precio_hoy - precio_ayer) / precio_ayer
# Para evitar un bucle, usamos slicing de NumPy.
precios_ayer = precios_acciones[:, :-1]  # Todas las filas, todas las columnas excepto la última.
precios_hoy = precios_acciones[:, 1:]   # Todas las filas, todas las columnas excepto la primera.

variacion_porcentual = (precios_hoy - precios_ayer) / precios_ayer * 100

print("\nVariación porcentual diaria (%):")
print(np.round(variacion_porcentual, 2))


# c) Aplicar funciones matemáticas como logaritmo, exponencial o normalización.

# Logaritmo natural de los precios
log_precios = np.log(precios_acciones)
print("\nLogaritmo natural de los precios:")
print(np.round(log_precios, 2))

# Normalización Min-Max: transforma los datos para que estén en el rango [0, 1].
# Fórmula: (X - min(X)) / (max(X) - min(X))
min_total = np.min(precios_acciones)
max_total = np.max(precios_acciones)
precios_normalizados = (precios_acciones - min_total) / (max_total - min_total)

print("\nPrecios normalizados (escala de 0 a 1):")
print(np.round(precios_normalizados, 2))


--- 2. Análisis y Transformación ---

Promedio de cada acción:
[156.24 147.79 144.34 134.71 137.32]

Valor máximo de cada acción:
[195.07 186.62 196.99 152.48 161.19]

Valor mínimo de cada acción:
[115.6  105.81 102.06 118.34 113.95]

Variación porcentual diaria (%):
[[ 41.92 -11.21  -7.7  -27.69]
 [ -8.47  76.37 -14.2    6.68]
 [ 93.02  -6.98 -33.84  -2.52]
 [ 10.21  16.91  -6.09  -9.83]
 [-29.31  13.4    5.74   6.57]]

Logaritmo natural de los precios:
[[4.92 5.27 5.15 5.07 4.75]
 [4.75 4.66 5.23 5.08 5.14]
 [4.63 5.28 5.21 4.8  4.77]
 [4.77 4.87 5.03 4.96 4.86]
 [5.08 4.74 4.86 4.92 4.98]]

Precios normalizados (escala de 0 a 1):
[[0.37 0.98 0.75 0.61 0.14]
 [0.14 0.04 0.89 0.61 0.72]
 [0.   1.   0.86 0.2  0.17]
 [0.17 0.3  0.53 0.43 0.29]
 [0.62 0.13 0.29 0.36 0.46]]


# 3. Optimización y selección de datos

In [8]:
# a) Utilizar indexación avanzada para extraer información específica.
# Ejemplo: Extraer el precio de la acción 1 (índice 0) en el día 3 (índice 2)
# y el precio de la acción 4 (índice 3) en el día 5 (índice 4).
# Pasamos una lista de índices de fila y una lista de índices de columna.
indices_filas = [0, 3]
indices_columnas = [2, 4]
precios_especificos = precios_acciones[indices_filas, indices_columnas]

print(f"\nPrecio de la acción 1 en el día 3: {np.round(precios_acciones[0, 2], 2)}")
print("\nUso de indexación avanzada:")
print(f"Precios de las acciones {indices_filas} en los días {indices_columnas}, respectivamente:")
print(np.round(precios_especificos, 2))


# b) Aplicar broadcasting para realizar operaciones sin necesidad de bucles.
# Broadcasting permite operar con arrays de diferentes formas.
# Ejemplo: Sumar una "comisión" fija de 0.5 a todas las transacciones.
comision = 0.5
precios_con_comision = precios_acciones + comision

print("\nAplicando Broadcasting para sumar una comisión de 0.5:")
# El escalar `comision` (0.5) se "difunde" (broadcasts) a cada elemento de la matriz.
print(np.round(precios_con_comision, 2))

# Ejemplo más avanzado: Restar el precio promedio de cada ACCIÓN a sus precios diarios.
# `promedio_por_accion` es un array de (5,), `precios_acciones` es (5, 5).
# NumPy no puede restar directamente (5,) de (5, 5). Debemos darle la forma correcta.
# Usamos `reshape(5, 1)` para que `promedio_por_accion` sea (5, 1).
# Ahora NumPy puede "difundir" este vector columna a través de las 5 columnas de la matriz de precios.
diferencia_vs_promedio = precios_acciones - promedio_por_accion.reshape(5, 1)

print("\nDiferencia de cada precio diario respecto al promedio de su acción (Broadcasting avanzado):")
print(np.round(diferencia_vs_promedio, 2))


Precio de la acción 1 en el día 3: 173.2

Uso de indexación avanzada:
Precios de las acciones [0, 3] en los días [2, 4], respectivamente:
[173.2  129.12]

Aplicando Broadcasting para sumar una comisión de 0.5:
[[137.95 195.57 173.7  160.37 116.1 ]
 [116.1  106.31 187.12 160.61 171.31]
 [102.56 197.49 183.74 121.73 118.68]
 [118.84 130.92 152.98 143.69 129.62]
 [161.69 114.45 129.71 137.14 146.11]]

Diferencia de cada precio diario respecto al promedio de su acción (Broadcasting avanzado):
[[-18.78  38.83  16.96   3.63 -40.64]
 [-32.19 -41.98  38.83  12.32  23.02]
 [-42.28  52.65  38.9  -23.11 -26.16]
 [-16.37  -4.29  17.76   8.48  -5.59]
 [ 23.87 -23.37  -8.1   -0.68   8.29]]


# 4. Comparación con otros métodos
## Claridad del código:
* Numpy: El código es conciso y expresivo. Operaciones como np.mean(axis=1) describen directamente la intención.
* Codigo normal: Se necesitan bucles anidados que oscurecen la intención matemática de la operación
## Rendimiento:
-  Numpy: Realiza "operaciones vectorizadas", procesando bloques enteros de memoria a la vez en lugar de elemento por elemento.
- Codigo normal: Cada iteración de un bucle for de Python tiene una sobrecarga significativa.
## Memoria:
- Numpy: Los arrays de NumPy almacenan elementos del mismo tipo de datos en un bloque contiguo de memoria
- Codigo normal: Las listas de Python son flexibles y pueden contener objetos de diferentes tipos, lo que implica una mayor sobrecarga de memoria para cada elemento.

## Conclusión:
Para el análisis de datos numéricos, especialmente con grandes volúmenes de datos, NumPy no solo hace que el código sea más limpio y fácil de escribir, sino que es fundamentalmente más rápido y eficiente en términos de memoria que usar las estructuras de datos básicas de Python.
